export const SEQUELIZE_PROVIDER = 'SEQUELIZE';
export const TOURS_REPOSITORY = 'TOURS_REPOSITORY';
export const USERS_REPOSITORY = 'USERS_REPOSITORY';
export const ROLES_REPOSITORY = 'ROLES_REPOSITORY';