export type Tour = {
  id: number;
  cityDepartureId: string;
  cityArrivalId: string;
  countryDepartureId: string;
  countryArrivalId: string;
  hotelId: string;
  datesDeparture: string[];
  nightsAmount: number;
  price: number;
  currency: string;
  guests: number;
  description: string;
  rating: number;
  image: string;
  cityDeparture: string;
  cityArrival: string;
  countryArrival: string;
  destination: { lat: number; lng: number } | null;
};
